/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/button/Button.vue')['default']
    NumberAnimate: typeof import('./components/numberAnimate/NumberAnimate.vue')['default']
    Pie: typeof import('./components/pie/Pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleBox: typeof import('./components/scaleBox/ScaleBox.vue')['default']
    SelectAll: typeof import('./components/selectAll/SelectAll.vue')['default']
    Test: typeof import('./components/numberAnimate/test.vue')['default']
  }
}
